name: Bug Report
description: Report an Virtuoso OpenSource bug
labels: [bug, unverified]
body:
- type: textarea
  attributes:
    label: Actual Behavior
    description: A clear description of what actually happens.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true
- type: markdown
  attributes:
    value: '> **Tip**: You can attach images or log files to textareas by clicking to highlight and then dragging files in.'
- type: textarea
  attributes:
    label: DataBase status report
    description: Provide output from `status()` command.
- type: textarea
  attributes:
    label: Call stacks
    description: |
      If you are reporting crash error include call stacks from core dump if available.
      If you are observing unexpected error from built-in functions, 
      then enable PL call stack for exceptions e.g. `__dbf_set('callstack_on_exception',2)`, 
      error logging `trace_on('errors')` and provide output from error and server log file. 
- type: textarea
  attributes:
    label: Executon(Query) plan and/or execution profile
    description: |
      If you are reporting unexpected result or unexpected execution time,
      provide output from `explain()` and/or `profile()` command. 
      You can also use command-line `isql` tool and use `set explain on` and `set profile on` (note: do not set both at same time).
- type: textarea
  attributes:
    label: Reproduction Steps
    description: Provide steps to reproduce the behavior
    placeholder: |
      1. Go to '...'
      2. Do DDL/DML '....'
      3. Execute '....'
      4. See error
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    options:
      - label: I have searched the [issue tracker](https://www.github.com/imitko/virtuoso-opensource/issues) for this problem.
        required: true
- type: textarea
  attributes:
    label: Additional Information
    description: If your problem needs further explanation, please add more information here.
- type: input
  attributes:
    label: Virtuoso OpenSource Version
    description: What version of Chat are you using?
    placeholder: "7.2.10"
  validations:
    required: true
- type: dropdown
  attributes:
    label: What operating system are you using?
    options:
      - Windows
      - macOS
      - Ubuntu
      - Other Linux
      - Other (specify below)
  validations:
    required: true
- type: input
  attributes:
    label: Operating System Version
    description: |-
      What operating system version are you using?
      On Windows, click Start button > Settings > System > About.
      On macOS, click the Apple Menu > About This Mac.
      On Linux, use `lsb_release` or `uname -a`.
    placeholder: "e.g. Windows 10 version 1909, macOS Catalina 10.15.7, or Ubuntu 20.04"
  validations:
    required: true
- type: input
  attributes:
    label: Installation method
    description: How did you install Virtuoso OpenSource?
    placeholder: "e.g. download from ..., docker image, own build from branch/tag"
  validations:
    required: true
- type: input
  attributes:
    label: Last Known Working Virtuoso OpenSource version
    description: What is the last version of Chat this worked in, if applicable?
    placeholder: "7.2.10"
